### ISSUE TITLE
Huge performance drop compared to Sauerbraten 

### ISSUE THREAD

**Issue by RicoP** [lsalzman/tesseract#1]
Hi,

I wouldn't call my Laptop a gaming PC, but Sauerbraten runs on my machine with 100-150 FPS. Tesseract however runs with all graphical effects turned off with 5-10 FPS. 

I tested the game under Ubuntu 11.04. I also get some shader errors: 

---

Using home directory: /home/rico/.tesseract/
Adding package directory: tesseract/
Adding package directory: sauerbraten/
init: sdl
init: net
init: game
init: video: mode
init: video: misc
init: gl
Renderer: GeForce 9200M GE/PCI/SSE2 (NVIDIA Corporation)
Driver: 2.1.2 NVIDIA 173.14.30
GLSL: 1.20 NVIDIA via Cg compiler
Rendering using the OpenGL GLSL shader path.
init: console
init: gl: effects
GLSL ERROR (VS:tetramodel)
(8) : error C1008: undefined variable "gl_ClipDistance"

1: uniform vec4 tetramodelclip;
2:  
3:             void main(void)
4:             {
5:                 gl_Position = ftransform();
6:                 #define opos gl_Vertex
7:  
8:                 gl_ClipDistance[0] = dot(opos, tetramodelclip); 
9:             }
10:  
GLSL ERROR (VS:alphashadowtetramodel)
(10) : error C1008: undefined variable "gl_ClipDistance"

1: uniform vec4 tetramodelclip;
2:         uniform vec4 texscroll;
3:  
4:             void main(void)
5:             {
6:                 gl_Position = ftransform();
7:                 #define opos gl_Vertex
8:  
9:                 gl_TexCoord[0].xy = gl_MultiTexCoord0.xy + texscroll.yz;
10:                 gl_ClipDistance[0] = dot(opos, tetramodelclip); 
11:             }
12:  
GLSL ERROR (VS:tetraworld)
(5) : error C1008: undefined variable "gl_ClipDistance"

1: uniform vec4 tetraclip;
2:     void main(void)
3:     {
4:         gl_Position = ftransform();
5:         gl_ClipDistance[0] = dot(gl_Vertex, tetraclip); 
6:     }
7: 
init: world
init: sound
init: cfg
init: mainloop

**Comment by RicoP** [comment]
It runs SLIGHTLY better  with windows 7 on the same machine...

**Comment by lsalzman** [comment]
Tesseract necessarily demands a better GPU than Sauerbraten. This is why I said in the announcement that I was ditching compatibility with older hardware: older hardware will not run this well, even if it can "run" it, technically.

**Comment by RicoP** [comment]
well makes sense, I guess I have to dust   my desktop...
