### ISSUE TITLE
/newmap error

### ISSUE THREAD

**Issue by ghost** [lsalzman/tesseract#13]
windows 8
Renderer: ATI Mobility Radeon HD 4300/4500 Series (ATI Technologies Inc.)
Driver: 3.3.11653 Compatibility Profile Context
GLSL: 3.30
Rendering using the OpenGL GLSL shader path.
![newmaperror](https://f.cloud.github.com/assets/3679845/188272/5fa1cc1a-7dd9-11e2-9b66-07dafc6d76c2.png)
After September 12-15

**Comment by lsalzman** [comment]
Not enough info about what caused this to do anything about it.
