### ISSUE TITLE
Entity and player names don't display. Intentional?

### ISSUE THREAD

**Issue by kroltan** [lsalzman/tesseract#16]
At least in Sauerbraten, people have their names over their heads, their chat comes out of them and entities have their names inside the boundary box. In Tesseract, there are no such things. It compromises editing a lot, because you have to point at every entity to see their name in the stats area, and players are unidentifiable. I don't know if this is intentional, and if it isn't, here are my specs:
Windows 7 Ultimate (64bit)
Intel Pentium E5800 @3.2GHz
Nvidia GTX 560 (driver version 314.07)
If it is intentional, a option would be nice.

Thanks in advance,
Kroltan Bahuman

**Comment by lsalzman** [comment]
Fixed.
