### ISSUE TITLE
Support for Cube 2 Mods

### ISSUE THREAD

**Issue by gotwig** [lsalzman/tesseract#17]
I'd like to see support for Cube 2 Mods.

E.g Red Eclipse would look gorgeous with tesseract modifications I guess.

Please give me some info :>

**Comment by lsalzman** [comment]
Red Eclipse is not a mod, it's a fork. And the source code is only coincidentally compatible with Sauerbraten right now, in the near future it is going to become incompatible with Sauerbraten media so that it can become its own game.
