### ISSUE TITLE
GLSL errors

### ISSUE THREAD

**Issue by inish777** [lsalzman/tesseract#18]
I did svn-checkout from cube2 repo and made symlink to packages/ directory. Tesseract launches and begins loading, but fails. 

Log:
https://gist.github.com/inish777/5219953

Distro: Ubuntu 12.10 x86_64

Will provide any needed information.

**Comment by lsalzman** [comment]
Not an issue with the code here. The fact that the variable msaasamples doesn't exist indicates you did not actually compile and install Tesseract's source code that matches the shaders it is trying to use.

**Comment by inish777** [comment]
Sorry, I thought I don't need to recompile tesseract.
