### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by Taurustar** [lsalzman/tesseract#19]
I have a little problem when I try to compile the tesseract under linux, I have all the dependences but in some point it fails for some Parameters are not declared at scope

![Screenshot - 03252013 - 08:26:45 PM](https://f.cloud.github.com/assets/3971084/301362/efa6179c-95cd-11e2-838a-06be435938f6.png)

**Comment by lsalzman** [comment]
You don't actually have all the dependencies. You need SDL 2, not SDL 1.2. Closing because this is not an issue with the code at all.

**Comment by Taurustar** [comment]
I hace SDL 2 but I still having the same problem anyway I'll check it again

**Comment by lheckemann** [comment]
That aside, why are you compiling it as root?

**Comment by Taurustar** [comment]
I tried with root and without root and I have the same problem

**Comment by lheckemann** [comment]
The point: you shouldn't be trying to compile it as root.

But as eihrul said: get SDL 2.

**Comment by Taurustar** [comment]
I have SDL2
