### ISSUE TITLE
Tesseract doesn't start

### ISSUE THREAD

**Issue by ghost** [lsalzman/tesseract#2]
Using home directory: /home/nazar/.tesseract/
Adding package directory: tesseract/
Adding package directory: sauerbraten/
init: sdl
init: net
init: game
init: video: mode
init: video: misc
init: gl
Renderer: Mesa DRI Mobile Intelťı GM45 Express Chipset  (Tungsten Graphics, Inc)
Driver: 2.1 Mesa 8.0.2
GLSL: 1.20
Rendering using the OpenGL GLSL shader path.
init: console
could not read "packages/fonts/default.cfg"
no default font specified

packages directory is symlinked, i can enter it

**Comment by lsalzman** [comment]
You are either not using an SVN checkout or not symlinking it properly. This is a user error, not a bug in the engine.
