### ISSUE TITLE
Tesseract Campaign ?

### ISSUE THREAD

**Issue by Memorix101** [lsalzman/tesseract#20]
Hello,
Why is there no compatibility to Sauerbraten's campaign mode in Tesseract ?
I love Tesseract, it looks awesome, but I really miss the campaign mode. I tried to add the missing code lines myself but it doesn't work for now  :P

**Comment by lsalzman** [comment]
As explained many times elsewhere, the purpose of Tesseract is not to be a compatible clone of Sauerbraten. In the future, it will diverge to the point of being a separate game. Closing this issue issue because it's not an actual issue.
