### ISSUE TITLE
How host a master server ?

### ISSUE THREAD

**Issue by Memorix101** [lsalzman/tesseract#21]
Hello :)
I wanna ask how can I host a master sever ?
I compiler the source code of the master server and got an tess_master.exe
But I don't know what to do next and it asked for a master.cfg ...
Hope you can help me. Thank you :)

**Comment by lsalzman** [comment]
Not an issue with the code. Use the cube forums.

**Comment by Memorix101** [comment]
I did that but nobody was able to answer me :(
