### ISSUE TITLE
Can't compile latest Tesseract on Ubuntu 12.10

### ISSUE THREAD

**Issue by Memorix101** [lsalzman/tesseract#23]
Hello,
I just downloaded the new version of Tesseract and always get this error:

"/bin/sh: 1: sdl2-config: not found
shared/cube.h:47:17: fatal error: SDL.h: No such file or directory
compilation terminated.
make: **\* [shared/cube.h.gch] Error 1
"

I don't know what's wrong because I was able to compile a previously build  ....

**Comment by Memorix101** [comment]
Would you be so friendly to give me an answer before you close that thread, please !

**Comment by q66** [comment]
You need SDL2, SDL2_mixer and SDL2_image. You'll have to compile them yourself.

**Comment by Memorix101** [comment]
OK: Done but where do I have to place them, now ? Make install doesn't work for me :P
But I Thought there already in Tess scr in the folder lib ?!

UPDATE

OK my new error :P

g++ -O3 -fomit-frame-pointer -Wall -fsigned-char -fno-exceptions -fno-rtti -Ishared -Iengine -Ifpsgame -Ienet/include -I/usr/X11R6/include `sdl2-config --cflags` -o shared/cube.tmp.h.gch shared/cube.h
shared/cube.h:48:23: fatal error: SDL_image.h: No such file or directory
compilation terminated.
