### ISSUE TITLE
Stray line in modelpreview::start

### ISSUE THREAD

**Issue by Hirato** [lsalzman/tesseract#24]
in rendergl.cpp

```
aspect = w/float(h);
fovy = 90;
curfov = 2*atan2(tan(fovy/2*RAD), 1/aspect)/RAD;
farplane = 1024;
vieww = min(gw, w);
viewh = min(gh, h);
aspect = 
ldrscale = 1;
ldrscaleb = ldrscale/255;
```

It should be pretty easy to spot, there's a line that just reads `aspect =` which means the aspect ratio is always forced to 1.
Just a little something I noticed whilst I was debugging my issue from earlier. It's quite inconsequential really.

**Comment by lsalzman** [comment]
Fixed.
