### ISSUE TITLE
bad interaction with execbind and MOUSE_WHEEL

### ISSUE THREAD

**Issue by Hirato** [lsalzman/tesseract#25]
Main.cpp

```
case SDL_MOUSEWHEEL:
    if(event.wheel.y > 0) processkey(-4, true);
    else if(event.wheel.y < 0) processkey(-5, true);
```

Console.cpp

```
void processkey(int code, bool isdown)
{
    keym *haskey = keyms.access(code);
    if(haskey && haskey->pressed) execbind(*haskey, isdown); // allow pressed keys to release
    else if(!g3d_key(code, isdown)) // 3D GUI mouse button intercept   
    {
        if(!consolekey(code, isdown))
        {
            if(haskey) execbind(*haskey, isdown);
        }
    }
}
```

Shouldn't take a genius to figure out what the two will culminate in.
Basically it is as so, because the scroll wheel never sends and events in which isdown is false, therefore after the first action that calls its bind, the key is forever considered pressed.
This means it takes priority over the other aspects, including GUI and console input, 3dgui uses this for scrolling in text widgets.

The best solution here is probably to send a key down event and follow it up with an immediate key up event, effectively mimicking SDL 1.2 behaviour.

**Comment by lsalzman** [comment]
Done.
