### ISSUE TITLE
loopfiles' duplicate detection is broken.

### ISSUE THREAD

**Issue by Hirato** [lsalzman/tesseract#26]
```
ICOMMAND(loopfiles, "rsse", (ident *id, char *dir, char *ext, uint *body),
{
    if(id->type!=ID_ALIAS) return;
    identstack stack;
    vector<char *> files;
    listfiles(dir, ext[0] ? ext : NULL, files);
    loopv(files)
    {
        char *file = files[i];
        bool redundant = false;
        loopj(i) if(!strcmp(files[j], file)) { redundant = true; break; }
        if(redundant) { delete[] file; continue; }
        if(i) 
        {
            if(id->valtype == VAL_STR) delete[] id->val.s;
            else id->valtype = VAL_STR;
            id->val.s = file;
        }
        else 
        {
            tagval t;
            t.setstr(file);
            pusharg(*id, t, stack);
            id->flags &= ~IDF_UNKNOWN;
        }
        execute(body);
    }
    if(files.length()) poparg(*id);
});
```

Basically, in the event a duplicate is detected, it is deleted, but the pointer is never set to NULL or removed, this means the files vector has an invalid pointer stored in it.

In addition, the segment of the loop below deletes and frees values which may come from this list. so basically, any pointers in the files vector earlier than i is invalid.
Presuming the user isn't being stupid, only the validity of the indexes of i-1 and up is ever valid.

I would advise replacing the following line

```
loopj(i) if(!strcmp(files[j], file)) { redundant = true; break; }
```

with this one

```
loopj(files.length() - i - 1) if(!strcmp(files[i + j + 1], file)) { redundant = true; break; }
```

but this will require some reworking of the logic below.
Alternatively you can split it into two loops, one to check for duplicates and remove them, and one to iterate.

**Comment by lsalzman** [comment]
Fixed.
