### ISSUE TITLE
keyboard layout issue in edit mode

### ISSUE THREAD

**Issue by ghost** [lsalzman/tesseract#27]
I'm using a azerty keyboard. WASD = ZQSD.
It works fine untill I go into edit mode, since Z = undo I cannot move forward.

**Comment by Calinou** [comment]
Don't forget /editbind q left

**Comment by ghost** [comment]
Ah okay. I was just confused since ZQSD worked out of the box like before (i take sdl2 changed things?) except in edit mode.
