### ISSUE TITLE
On Mac OS X tesseract spins in buildverts probably due to LLVM GCC bug, resulting in hung load map

### ISSUE THREAD

**Issue by tthomas6** [lsalzman/tesseract#3]
Attempting to run tesseract on Mac OS X Snow Leopard (compiled using XCode 3.2) spins in md5mesh::buildverts().  The symptoms for example are, when loading a map, the progress bar quickly gets "stuck" and the application hangs.  (To get "unstuck", press command-option-escape to bring up the Force Quit menu, select tesseract, and hit Return.)

Cutting to the chase, the reason is because the variable i (incremented by the loopi loop starting at line 58 of md5.h) keeps getting reset back to 1 every time line 66 is executed:

   pos.add(j.orient.rotate(w.pos).add(j.pos).mul(w.bias));

I broke said line into multiple lines:

   vec rvec = j.orient.rotate(w.pos);
   rvec.add(j.pos);
   rvec.mul(w.bias);
   pos.add(rvec);

That is, I created a local variable rvec and used that to perform the calculations.  Doing so caused the problem to go away.

Further research (i.e. web searches) indicated that the LLVM version of GCC may be at fault.  I switched compilation to GCC 4.2 from LLVM GCC 4.2 by right-clicking on the tesseract target in XCode, selecting Get Info from the contextual menu, selecting the Build tab, scrolling to the C/C++ Compiler Version and changing the value to GCC 4.2.  I removed my "fix" and recompiled, and the problem was gone.

Considering how LLVM works, it's fair to say it isn't properly (or safely) tracking the variable usage in the rather succinct line 58 of md5.h. ;)   Whether the target compiler of tesseract should be changed to GCC 4.2 from LLVM GCC 4.2 is up to the author.  However, I wanted to report this so that anyone else running into this problem will see a record of the problem, with the symptoms and workaround.

**Comment by fernLightning** [comment]
Thanks for the feedback.

Happily with xcode4+ llvm seems much more robust.
