### ISSUE TITLE
Tesseract on Mac OS X has moire patterns on textures in front of the player

### ISSUE THREAD

**Issue by tthomas6** [lsalzman/tesseract#4]
When running tesseract on Mac OS X Snow Leopard, some ugly texture artifacts occur on the distant planes perpendicular to the player eye vector; that is, the far walls directly in front of the player show a moire pattern (http://en.wikipedia.org/wiki/File:Moire_Lines.svg).  The moire pattern moves around in the typical way as the player moves.  (See http://www.youtube.com/watch?v=l5Sl_Lqpkvo for a generic example of what I mean.)

Note that I've compiled and run Sauerbraten Justice Edition and it doesn't have the display issue.  Also note that I've grabbed sauer-svn-rv4167, but unfortunately currently am having trouble getting it to work (odd and unhelpful linking errors, although it compiles fine), so I cannot verify yet if the problem is present in the newer source base.  Lastly, I have not verified if the problem is present on Windows or Linux.  (At the moment I'm concentrating on Mac OS X.)

I'm currently using XCode 3.2, and am running 10.6.8.  If you need more information, please let me know.

By the way, thanks for your (and the other developers') continued efforts to maintain the engine across platforms.  I appreciate it!

**Comment by JoshEngebretson** [comment]
I had this issue as well on both a Mac Pro with an ATI 5770 and a MacBook Air with Intel HD3000, I was able to remedy it with, if I recall correctly, the glineardepth variable.  I am not sure if this is a good "fix" or not... I didn't have much time to look into it.

**Comment by tthomas6** [comment]
Josh:  Good call!  Setting glineardepth to 1 (from the default 0 on my system) eliminated the texture moire patterns.  However...  It did not eliminate the artifacts on glass and in some other circumstances (I'm guessing certain texture overlays).  The best way to see this I've found so far is the map Justice.  Set glineardepth to 1, start the game, and hop into that map.  The large "screen" on the wall as well as the glass windows show the moire pattern, although the textured walls no longer do (thankfully).  Again, thanks Josh for the suggestion.

Now, I temporarily "disabled" renderglass() in engine/material.cpp by sticking a return at the start of the function and reran the map to verify that glass rendering was indeed the problem for glass.  It was (heh, not surprisingly :) ).  So something isn't right in that function, or perhaps drawglass() (called by renderglass()).  What I mean by not right is something in the normal texture rendering is avoiding the problem that renderglass() or drawglass() are not.  If someone has some ideas what to look for I can continue to investigate this.
