### ISSUE TITLE
Add a "make all lights static" option

### ISSUE THREAD

**Issue by Calinou** [lsalzman/tesseract#7]
This option would make all "dynamic" lights (those with arg5 = 0) static (no dynamic shadows). Good for older computers.

However, I think arg5 set to 3 would always set the light as dynamic regardless of setting. This would be useful where enabling this setting would give an advantage to a player (eg. light in front of a pickup, the light lights a whole room).

**Comment by lsalzman** [comment]
You can set smdynshadow 0 to do this. Currently the variable isn't persistent but it may be in the future.
