### ISSUE TITLE
Computer crash after pressing F5 in edit mode

### ISSUE THREAD

**Issue by gotwig** [lsalzman/tesseract#8]
I experimented a bit with making a level, and tried several "keys" for editing.

After I played a bit with height, textures and materials, I wanted to try F4, the models.

I accidently pressed F5, after that my whole computer just shut instantly down. It lost its power and its data.

After I tried to start my PC again, it beeped a bit longer than usual, around 3-4 seconds.

This is a very uncommon situation, for me as a Linux user.

I use the latest NVIDIA proprietary linux driver (310 Experimental I guess?, for steam), a Geforce® 240 GT, a 2,9 GHZ Pentium 4 Processor. My PC turns soon, to become 8 years old.

My linux distro is elementary Luna, its based on Ubuntu 12.04.3 LTS. I have worked partialy on my own to realize that distro.

**Comment by lsalzman** [comment]
All F5 does is save a map. The bug you experienced is not Tesseract, as Tesseract has no ability to forcefully shut down your computer in any way via OpenGL. The bug is in NV's drivers.
